### Listar todos os endereços
GET http://localhost:3000/address HTTP/1.1
content-type: application/json

### Listar um unico endereço
GET http://localhost:3000/address/2 HTTP/1.1
content-type: application/json

### Buscar por lat + long (raio padrão ~5km)
GET http://localhost:3000/address?lat=-22.0221&long=-47.8904 HTTP/1.1
content-type: application/json

### Buscar por lat + long com raio customizado
GET http://localhost:3000/address?lat=-22.02&long=-47.89&radius=0.2 HTTP/1.1
content-type: application/json

### Buscar só por lat
GET http://localhost:3000/address?lat=-23.5505 HTTP/1.1
content-type: application/json

### Buscar só por long
GET http://localhost:3000/address?long=-46.6333 HTTP/1.1
content-type: application/json

### Combinar com filtro de usuário
GET http://localhost:3000/address?lat=-23.5505&long=-46.6333&user=1 HTTP/1.1
content-type: application/json

### Filtar por companhia
GET http://localhost:3000/address?company= HTTP/1.1
content-type: application/json

### Listar por categoria
GET http://localhost:3000/address?category= HTTP/1.1
content-type: application/json

### Listar por favoritos
GET http://localhost:3000/address?favorites= HTTP/1.1
content-type: application/json

### editando todos os campos do endereço
PUT  http://localhost:3000/address/1 HTTP/1.1
content-type: application/json

{
    "place":    "Av. São Carlos, Centro",
    "number":   "1242",
    "zipcode":  "13566-330", 
    "lat":      -22.022011888377065,
    "long":     -47.8904711,
}

### editando apenas um campo do endereço
PUT  http://localhost:3000/address/1 HTTP/1.1
content-type: application/json

{
    "place":    "Av. São Carlos, Centro",
    "number":   "1242",
    "zipcode":  "13566-330", 
    "lat":      -22.022011888377065,
    "long":     -47.8904711,
}

### editando apenas um endereço
DELETE http://localhost:3000/address/1 HTTP/1.1
content-type: application/json


### 
POST http://localhost:3000/address
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="place"

Av. São Carlos, Centro
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="number"

1242
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="zipcode"

13566-330
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="lat"

-22.022011888377065
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="long"

-47.8904711
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="pizza.jpg"
Content-Type: image/jpeg

< ./pizza.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--