@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInR5cGUiOiJvd25lciIsImVtYWlsIjoibWFyY2l1c0BsYWdhcnRvLmNvbSIsIm5hbWUiOiJNYXJjaXVzIEh1bWJlcnRvIiwiaWF0IjoxNzc2OTg1NTQ4LCJleHAiOjE3NzcwNzE5NDh9.qGfrZbZkQJqZ4hfiUbx2V-1CYAY6-kjG5LgIxJ5UM-k

### Listar todos os endereços
GET https://voyagegabi.onrender.com/address HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

### Listar um unico endereço
GET https://voyagegabi.onrender.com/address/2 HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

### Buscar por lat + long (raio padrão ~5km)
GET https://voyagegabi.onrender.com/address?lat=-22.0221&long=-47.8904 HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

### Buscar por lat + long com raio customizado
GET https://voyagegabi.onrender.com/address?lat=-22.02&long=-47.89&radius=0.2 HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

### Buscar só por lat
GET https://voyagegabi.onrender.com/address?lat=-23.5505 HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

### Buscar só por long
GET https://voyagegabi.onrender.com/address?long=-46.6333 HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

### Combinar com filtro de usuário
GET https://voyagegabi.onrender.com/address?lat=-23.5505&long=-46.6333&user=1 HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

### Filtar por companhia
GET https://voyagegabi.onrender.com/address?company= HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

### Listar por categoria
GET https://voyagegabi.onrender.com/address?category= HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

### Listar por favoritos
GET https://voyagegabi.onrender.com/address?favorites= HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

### editando todos os campos do endereço
PUT  https://voyagegabi.onrender.com/address/1 HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
    "place":    "Av. São Carlos, Centro",
    "number":   "1242",
    "zipcode":  "13566-330", 
    "lat":      -22.022011888377065,
    "long":     -47.8904711,
}

### editando apenas um campo do endereço
PUT  https://voyagegabi.onrender.com/address/1 HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
    "place":    "Av. São Carlos, Centro",
    "number":   "1242",
    "zipcode":  "13566-330", 
    "lat":      -22.022011888377065,
    "long":     -47.8904711,
}

### editando apenas um endereço
DELETE https://voyagegabi.onrender.com/address/15 HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json


### 
POST https://voyagegabi.onrender.com/address
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="place"

Florisberto aparecido da silva, Cidade aracy
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="number"

189
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="zipcode"

13573-168
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="lat"

-22.058444234048984
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="long"

-47.90917365444325
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="pizza.jpg"
Content-Type: image/jpeg

< ./pizza.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--