@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInR5cGUiOiJvd25lciIsImVtYWlsIjoicGlwb3F1aW5hMTIzQGxhZ2FydG8uY29tIiwibmFtZSI6IkpvbmFzIFBpcG9jYSIsImlhdCI6MTc3Njk5MzAxMSwiZXhwIjoxNzc3MDc5NDExfQ.cwi_MK6KN8h_B_foTVP32LvqoVl8TI03LvUPdk6gJKs


### criando uma Company
POST http://localhost:3000/company HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
    "name":     "Teste4",
    "category": "Outros",
    "cnpj":     "07.358.445/0001-97",
    "evaluate": 4.6,
    "places":   "Pedro Sampaio, 1567"
}
### cnpj ta sem unique

### Listar todos as companies

GET http://localhost:3000/company HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

### Listar todos as companies sem estar logado tbm

GET https://voyage-i5zo.onrender.com/company HTTP/1.1
content-type: application/json

### Lista uma unica company

GET https://voyage-i5zo.onrender.com/company/3 HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

### Filtro das companies

GET https://voyage-i5zo.onrender.com/company?name=que HTTP/1.1
content-type: application/json

### Filtro das adrress

GET https://voyage-i5zo.onrender.com/company?places=Ave HTTP/1.1
content-type: application/json

### Filtro das categorias

GET https://voyage-i5zo.onrender.com/company?category=chur HTTP/1.1
content-type: application/json

### Editar apenas um campo do usuario

PUT https://voyage-i5zo.onrender.com/company/1 HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
    "name":     "Tabajara Grill",
    "category": "Lanchonete",
    "cnpj":     "61.851.929/0001-00",
    "evaluate": 0,
    "places":   "Avenida São Carlos, Centro"
}

### Editar todos os campos do usuario

PUT https://voyage-i5zo.onrender.com/company/2 HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
    "name":     "Casa do Pão de Queijo",
    "category": "Lanchonete",
    "cnpj":     "61.851.929/0001-00",
    "evaluate": 0,
    "places":   "Avenida São Carlos, Centro"
}


### Deletando campo de usuario

DELETE https://voyage-i5zo.onrender.com/company/3 HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

