@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjcsInR5cGUiOiJvd25lciIsImVtYWlsIjoibGF1cmFAZ21haWwuY29tIiwibmFtZSI6IkxhdXJhIiwiaWF0IjoxNzc3NDI0NDE5LCJleHAiOjE3Nzc1MTA4MTl9.8pH4_wNJYCYGqe-w6AN3qz6rk6kDQF8wCJ9ChIXTDxI

### refazendo o cadastro que cometeu suicidio.
POST https://voyagegabi.onrender.com/user HTTP/1.1
content-type: application/json

{
    "name":         "kevin",
    "type":         "owner",
    "email":        "jonasbixa@gmail.com",
    "password":     "B@tatinha123",
    "phone":        "19997404538",
    "cpf":          "886.272.590-62" 
}
### cpf ta sem unique

### Login do usuario marcius
POST https://voyagegabi.onrender.com/user/login HTTP/1.1
content-type: application/json

{
    "email":        "jonasbixa@gmail.com",
    "password":     "B@tatinha123"
}

### Login do  2
POST https://voyagegabi.onrender.com/user/login HTTP/1.1
content-type: application/json

{
    "email":        "jonasbixa@gmail.com",
    "password":     "B@tatinha123"
}


### listar todos os usuarios.
GET https://voyagegabi.onrender.com/user/ HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

### listando um unico usuario.
GET https://voyagegabi.onrender.com/user/2 HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

### 
GET https://voyagegabi.onrender.com/user?email=jjunior234534@berinjela.com HTTP/1.1
content-type: application/json

### 
GET https://voyagegabi.onrender.com/user?name HTTP/1.1
content-type: application/json

### 
GET https://voyagegabi.onrender.com/user?type HTTP/1.1
content-type: application/json

### 
GET https://voyagegabi.onrender.com/user?signature HTTP/1.1
content-type: application/json

### editanto todos os campos de usuario.
PUT https://voyagegabi.onrender.com/user/1 HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{

  "name":        "Laura",
  "type":        "owner",
  "email":       "lauraa@gmail.com",
  "password":    "B@tatinha123",
  "phone":       "19844453838"

}

### editanto apenas um campo de usuario.
PUT https://voyagegabi.onrender.com/user/1 HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{

  "name":        "Kevingay",
  "type":        "owner",
  "email":       "kevuinsaf@gmail.com",
  "password":    "B@tatinha123"

}

### Deletar um usuario
DELETE https://voyagegabi.onrender.com/user/1 HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json