@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInR5cGUiOiJvd25lciIsImVtYWlsIjoibWFyY2l1c0BsYWdhcnRvLmNvbSIsIm5hbWUiOiJNYXJjaXVzIEh1bWJlcnRvIiwiaWF0IjoxNzc2OTg1NTQ4LCJleHAiOjE3NzcwNzE5NDh9.qGfrZbZkQJqZ4hfiUbx2V-1CYAY6-kjG5LgIxJ5UM-k

### refazendo o cadastro que cometeu suicidio.
POST https://voyagegabi.onrender.com/user HTTP/1.1
content-type: application/json

{
    "name":         "Amanda",
    "type":         "owner",
    "email":        "amanda@gmail.com",
    "password":     "B@tatinha123",
    "phone":        "19844453838",
    "cpf":          "897.125.190-58" 
}
### cpf ta sem unique

### Login do usuario marcius
POST https://voyagegabi.onrender.com/user/login HTTP/1.1
content-type: application/json

{
    "email":        "amanda@gmail.com",
    "password":     "B@tatinha123"
}

### Login do  humbertol
POST https://voyagegabi.onrender.com/user/login HTTP/1.1
content-type: application/json

{
    "email":        "matheus@lagarto.com",
    "password":     "B@tatinha123"
}


### listar todos os usuarios.
GET https://voyage-kevin.onrender.com/user/ HTTP/1.1
content-type: application/json

### listando um unico usuario.
GET https://voyagegabi.onrender.com/user/2 HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

### 
GET https://voyagegabi.onrender.com/user?email=jjunior234534@berinjela.com HTTP/1.1
content-type: application/json

### 
GET https://voyagegabi.onrender.com/user?name HTTP/1.1
content-type: application/json

### 
GET https://voyagegabi.onrender.com/user?type HTTP/1.1
content-type: application/json

### 
GET https://voyagegabi.onrender.com/user?signature HTTP/1.1
content-type: application/json

### editanto todos os campos de usuario.
PUT https://voyagegabi.onrender.com/user/1 HTTP/1.1
content-type: application/json

{

  "name":        "João Junior",
  "type":        "user",
  "email":       "jjunior234534@berinjela.com",
  "password":    "jjjunior8538",
  "phone":       "69696969696"

}

### editanto apenas um campo de usuario.
PUT https://voyagegabi.onrender.com/user/1 HTTP/1.1
content-type: application/json

{

  "name":        "Paulo",
  "type":        "Owner",
  "email":       "Pauloportas43@gmail.com",
  "password":    "ppaulo234"

}

### Deletar um usuario
DELETE https://voyagegabi.onrender.com/user/2 HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json